"""Signal Data Transfer Object."""

from dataclasses import dataclass, field
from datetime import datetime

from core.models import OrderType, Timeframe


@dataclass(frozen=True)
class SignalDTO:
    """DTO representing a raw trading signal generated by a strategy policy."""

    signal_id: str
    symbol: str
    timeframe: Timeframe
    order_type: OrderType
    entry_price: float
    stop_loss: float | None = None
    take_profit: float | None = None
    timestamp: datetime = field(default_factory=datetime.now)
